
[[constraint]]
  branch = "master"
  name = "github.com/Clever/syslogparser"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "golang.org/x/time"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.24.0"
